/* @Authors
 * Student Names: Taha Çali, Ahmet Enes Çiğdem, Ali Eren Çiftçi
 * Student IDs: 150220050, 150220079, 150220022
 *
 * Generated by: Claude (LLM2) — Edited Prompt
 */
package phase_2.llm2.edited;

import java.util.*;

/**
 * BookScan analyzes text documents to find word occurrences by length
 * and track their line positions.
 *
 * <p>It processes multi-line text (lines separated by {@code \n}) to:
 * <ol>
 *   <li>Find all words of a specified length</li>
 *   <li>Count how many times each word appears (including overlapping occurrences)</li>
 *   <li>Track which line numbers (1-indexed) each word appears on</li>
 *   <li>Support case-insensitive matching via case transformation</li>
 * </ol>
 *
 * <p>Integrates three HumanEval utility methods internally:
 * {@link #howManyTimes}, {@link #strlen}, and {@link #flipCase}.
 */
public class BookScan {

    // =========================================================================
    // Task #18 — howManyTimes (substring counting with overlapping)
    // =========================================================================

    /**
     * Counts how many times {@code substring} appears in {@code text},
     * <strong>including overlapping occurrences</strong>.
     *
     * <pre>
     * howManyTimes("aaaa", "aa") → 3  (positions 0, 1, 2)
     * howManyTimes("",     "a")  → 0
     * howManyTimes("aaa",  "a")  → 3
     * </pre>
     *
     * @param text      the text to search within
     * @param substring the substring to find
     * @return the number of (possibly overlapping) occurrences, or 0 if either
     *         argument is {@code null} or {@code substring} is empty
     */
    public int howManyTimes(String text, String substring) {
        if (text == null || substring == null || substring.isEmpty()) {
            return 0;
        }
        int count = 0;
        int idx = 0;
        while ((idx = text.indexOf(substring, idx)) != -1) {
            count++;
            idx++; // advance by 1 to allow overlapping matches
        }
        return count;
    }

    // =========================================================================
    // Task #23 — strlen (string length)
    // =========================================================================

    /**
     * Returns the length of the given string.
     *
     * <pre>
     * strlen("")    → 0
     * strlen("abc") → 3
     * </pre>
     *
     * @param string the input string
     * @return the length of {@code string}, or 0 if {@code null}
     */
    public int strlen(String string) {
        if (string == null) {
            return 0;
        }
        return string.length();
    }

    // =========================================================================
    // Task #27 — flipCase (case inversion)
    // =========================================================================

    /**
     * Flips lowercase characters to uppercase and uppercase to lowercase.
     * Non-alphabetic characters remain unchanged.
     *
     * <pre>
     * flipCase("Hello")  → "hELLO"
     * flipCase("Hello!") → "hELLO!"
     * </pre>
     *
     * @param string the input string
     * @return the string with each letter's case inverted, or {@code null} if
     *         the input is {@code null}
     */
    public String flipCase(String string) {
        if (string == null) {
            return null;
        }
        StringBuilder sb = new StringBuilder(string.length());
        for (char c : string.toCharArray()) {
            if (Character.isLowerCase(c)) {
                sb.append(Character.toUpperCase(c));
            } else if (Character.isUpperCase(c)) {
                sb.append(Character.toLowerCase(c));
            } else {
                sb.append(c);
            }
        }
        return sb.toString();
    }

    // =========================================================================
    // Primary integration method
    // =========================================================================

    /**
     * Scans multi-line text for words of a given length. For each unique word
     * found (case-insensitive), it records:
     * <ul>
     *   <li><b>"count"</b> — total number of (overlapping) occurrences across
     *       all lines (as {@code Integer})</li>
     *   <li><b>"lines"</b> — sorted set of 1-indexed line numbers where the
     *       word appears (as {@code Set<Integer>})</li>
     * </ul>
     *
     * <p><b>Processing pipeline per line:</b>
     * <ol>
     *   <li>Split line into tokens by whitespace</li>
     *   <li>Strip non-alphanumeric characters from each token</li>
     *   <li>Use {@link #strlen} to filter tokens matching {@code targetLength}</li>
     *   <li>Use {@link #flipCase} to normalize to a lowercase key for
     *       case-insensitive grouping</li>
     *   <li>Use {@link #howManyTimes} to count occurrences of the word in the
     *       normalized line</li>
     * </ol>
     *
     * @param text         the multi-line text to scan (lines separated by
     *                     {@code \n})
     * @param targetLength the desired word length to search for; must be &gt; 0
     * @return a map keyed by normalized (lowercase) words, each mapped to a
     *         {@code Map<String, Object>} with keys {@code "count"} and
     *         {@code "lines"}. Returns an empty map for null/empty text or
     *         non-positive target length.
     * @throws IllegalArgumentException if {@code targetLength} is negative
     */
    public Map<String, Map<String, Object>> scanByWordLength(String text, int targetLength) {
        Map<String, Map<String, Object>> results = new LinkedHashMap<>();

        if (text == null || text.isEmpty() || targetLength <= 0) {
            return results;
        }

        String[] lines = text.split("\n");

        for (int lineIdx = 0; lineIdx < lines.length; lineIdx++) {
            String line = lines[lineIdx];
            int lineNumber = lineIdx + 1; // 1-indexed

            // Normalize entire line for case-insensitive substring counting
            String normalizedLine = toLowerUsingFlipCase(line);

            // Split line into raw tokens by whitespace
            String[] tokens = line.split("\\s+");

            // Track which normalized words we've already counted on this line
            // to avoid double-counting when the same word appears multiple times
            // as separate tokens
            Set<String> processedOnLine = new HashSet<>();

            for (String token : tokens) {
                if (token.isEmpty()) {
                    continue;
                }

                // Strip punctuation so "hello," and "hello" are the same word
                String cleanWord = token.replaceAll("[^a-zA-Z0-9]", "");

                // Use strlen (Task #23) to check length
                if (strlen(cleanWord) != targetLength) {
                    continue;
                }

                // Normalize to lowercase using flipCase (Task #27) for grouping
                String key = toLowerUsingFlipCase(cleanWord);

                if (processedOnLine.contains(key)) {
                    continue; // already counted this word on this line
                }
                processedOnLine.add(key);

                // Use howManyTimes (Task #18) to count occurrences in this line
                int occurrences = howManyTimes(normalizedLine, key);

                // Aggregate into results
                Map<String, Object> entry = results.computeIfAbsent(key, k -> {
                    Map<String, Object> m = new LinkedHashMap<>();
                    m.put("count", 0);
                    m.put("lines", new TreeSet<Integer>());
                    return m;
                });

                entry.put("count", (int) entry.get("count") + occurrences);

                @SuppressWarnings("unchecked")
                Set<Integer> lineSet = (Set<Integer>) entry.get("lines");
                lineSet.add(lineNumber);
            }
        }

        return results;
    }

    // =========================================================================
    // Internal helper
    // =========================================================================

    /**
     * Converts a string to lowercase by leveraging {@link #flipCase}.
     * For each character: if it is uppercase, {@code flipCase} converts it to
     * lowercase; otherwise the character is kept as-is.
     *
     * @param s the input string
     * @return the lowercase version, or {@code null} if input is {@code null}
     */
    private String toLowerUsingFlipCase(String s) {
        if (s == null) {
            return null;
        }
        StringBuilder sb = new StringBuilder(s.length());
        for (char c : s.toCharArray()) {
            if (Character.isUpperCase(c)) {
                sb.append(flipCase(String.valueOf(c)));
            } else {
                sb.append(c);
            }
        }
        return sb.toString();
    }
}
