/* @Authors
 * Student Names: Taha Çali, Ahmet Enes Çiğdem, Ali Eren Çiftçi
 * Student IDs: 150220050, 150220079, 150220022
 *
 * Generated by: Gemini Pro (LLM1) — Unmodified Prompt
 */

package phase_2.llm1.unmodified;

import java.util.*;

public class BookScan {

    // ==========================================
    // Task #18 — Substring Counting
    // ==========================================
    /**
     * Find how many times a given substring can be found in the original string. 
     * Counts overlapping cases.
     */
    public int howManyTimes(String string, String substring) {
        if (string == null || substring == null || substring.isEmpty()) {
            return 0;
        }
        int count = 0;
        int index = 0;
        
        while ((index = string.indexOf(substring, index)) != -1) {
            count++;
            index++; // Increment by 1 to catch overlapping substrings
        }
        return count;
    }

    // ==========================================
    // Task #23 — String Length
    // ==========================================
    /**
     * Return length of given string
     */
    public int strlen(String string) {
        if (string == null) {
            return 0;
        }
        return string.length();
    }

    // ==========================================
    // Task #27 — Flip Case
    // ==========================================
    /**
     * For a given string, flip lowercase characters to uppercase 
     * and uppercase to lowercase.
     */
    public String flipCase(String string) {
        if (string == null) {
            return null;
        }
        StringBuilder flipped = new StringBuilder();
        
        for (char c : string.toCharArray()) {
            if (Character.isUpperCase(c)) {
                flipped.append(Character.toLowerCase(c));
            } else if (Character.isLowerCase(c)) {
                flipped.append(Character.toUpperCase(c));
            } else {
                flipped.append(c); // Keep non-alphabetic characters as-is
            }
        }
        return flipped.toString();
    }

    // ==========================================
    // Primary Integration Method
    // ==========================================
    /**
     * Scans text for words of a target length, calculates their frequencies, 
     * logs the lines they appear on, and applies flipCase for the final report.
     */
    public Map<String, WordStats> analyzeText(String text, int targetLength) {
        Map<String, WordStats> results = new HashMap<>();
        if (text == null || text.isEmpty()) {
            return results;
        }

        // Split text into individual lines
        String[] lines = text.split("\\r?\\n");

        for (int i = 0; i < lines.length; i++) {
            // Extract words (splitting by any non-word characters)
            String[] words = lines[i].split("\\W+");

            for (String word : words) {
                // 1. Check if the word matches the desired length
                if (strlen(word) == targetLength) {
                    
                    if (!results.containsKey(word)) {
                        // 2. Count total occurrences in the entire text
                        int totalOccurrences = howManyTimes(text, word);
                        
                        // 3. Flip the case of the matched word
                        String flipped = flipCase(word);
                        
                        results.put(word, new WordStats(word, flipped, totalOccurrences));
                    }
                    // Add the 1-based line number to the tracker
                    results.get(word).addLine(i + 1);
                }
            }
        }
        return results;
    }

    // ==========================================
    // Helper Data Structure
    // ==========================================
    public static class WordStats {
        public String originalWord;
        public String flippedWord;
        public int totalOccurrences;
        public Set<Integer> linesAppeared;

        public WordStats(String originalWord, String flippedWord, int totalOccurrences) {
            this.originalWord = originalWord;
            this.flippedWord = flippedWord;
            this.totalOccurrences = totalOccurrences;
            this.linesAppeared = new TreeSet<>(); // Ensures lines are sorted and unique
        }

        public void addLine(int line) {
            this.linesAppeared.add(line);
        }

        @Override
        public String toString() {
            return String.format("Word: '%s' (Flipped: '%s') | Occurrences: %d | Lines: %s",
                    originalWord, flippedWord, totalOccurrences, linesAppeared);
        }
    }
}