/* @Authors
 * Student Names: Taha Çali, Ahmet Enes Çiğdem, Ali Eren Çiftçi
 * Student IDs: 150220050, 150220079, 150220022
 *
 * Generated by: Gemini (LLM1) — Edited Prompt
 */
package phase_2.llm1.edited;


import java.util.*;

/**
 * BookScan analyzes text documents to find word occurrences by length and tracks their line positions.
 */
public class BookScan {

    /**
     * Scans multi-line text to find all words of a specific length, counts their occurrences,
     * and records the line numbers where they appear.
     *
     * @param text         The input text to analyze.
     * @param targetLength The word length to search for.
     * @return A map where keys are the normalized matching words and values are a map containing
     * the "count" (Integer) and the "lines" (Set of Integers) where the word appears.
     */
    public static Map<String, Map<String, Object>> scanByWordLength(String text, int targetLength) {
        Map<String, Map<String, Object>> results = new HashMap<>();

        if (text == null || text.trim().isEmpty() || targetLength <= 0) {
            return results; // Return empty results for empty or invalid input
        }

        String[] lines = text.split("\n");

        for (int i = 0; i < lines.length; i++) {
            int lineNumber = i + 1; // 1-indexed line tracking
            String line = lines[i];

            // Normalize the entire line for case-insensitive comparison
            String normalizedLine = normalizeToLowerCase(line);

            // Split line into words
            String[] words = line.split("\\s+");
            Set<String> processedWordsInLine = new HashSet<>();

            for (String rawWord : words) {
                // Strip punctuation for accurate length measurement
                String cleanWord = rawWord.replaceAll("[^a-zA-Z0-9]", "");

                if (strlen(cleanWord) == targetLength) {
                    String normalizedWord = normalizeToLowerCase(cleanWord);

                    // Ensure we only process each unique target word once per line 
                    // to prevent duplicate counting during the word loop
                    if (!processedWordsInLine.contains(normalizedWord)) {
                        processedWordsInLine.add(normalizedWord);

                        // Use howManyTimes to count overlaps / occurrences in the normalized line
                        int occurrencesInLine = howManyTimes(normalizedLine, normalizedWord);

                        if (occurrencesInLine > 0) {
                            results.putIfAbsent(normalizedWord, new HashMap<>());
                            Map<String, Object> stats = results.get(normalizedWord);

                            stats.putIfAbsent("count", 0);
                            stats.putIfAbsent("lines", new TreeSet<Integer>()); // TreeSet keeps lines sorted and unique

                            int currentCount = (int) stats.get("count");
                            stats.put("count", currentCount + occurrencesInLine);

                            @SuppressWarnings("unchecked")
                            Set<Integer> lineSet = (Set<Integer>) stats.get("lines");
                            lineSet.add(lineNumber);
                        }
                    }
                }
            }
        }
        return results;
    }

    /**
     * Counts how many times a substring appears in a given text, including overlapping occurrences.
     *
     * @param text      The text to search within.
     * @param substring The substring to find.
     * @return The number of occurrences, or 0 if inputs are null/empty.
     */
    public static int howManyTimes(String text, String substring) {
        if (text == null || substring == null || substring.isEmpty()) {
            return 0;
        }
        int count = 0;
        int idx = 0;
        while ((idx = text.indexOf(substring, idx)) != -1) {
            count++;
            idx++; // Increment by 1 to count overlapping occurrences
        }
        return count;
    }

    /**
     * Returns the length of the given string.
     *
     * @param string The input string.
     * @return The length of the string, or 0 if null.
     */
    public static int strlen(String string) {
        if (string == null) {
            return 0;
        }
        return string.length();
    }

    /**
     * Flips lowercase characters to uppercase and uppercase to lowercase.
     * Non-alphabetic characters remain unchanged.
     *
     * @param string The input string.
     * @return The string with inverted character casing.
     */
    public static String flipCase(String string) {
        if (string == null) {
            return null;
        }
        StringBuilder result = new StringBuilder(string.length());
        for (char c : string.toCharArray()) {
            if (Character.isLowerCase(c)) {
                result.append(Character.toUpperCase(c));
            } else if (Character.isUpperCase(c)) {
                result.append(Character.toLowerCase(c));
            } else {
                result.append(c);
            }
        }
        return result.toString();
    }

    /**
     * Helper method that utilizes flipCase to normalize a string to lowercase.
     * This explicitly satisfies the requirement to use flipCase for case normalization.
     *
     * @param text The input text.
     * @return The text normalized to lowercase.
     */
    private static String normalizeToLowerCase(String text) {
        if (text == null) {
            return null;
        }
        StringBuilder result = new StringBuilder(text.length());
        for (char c : text.toCharArray()) {
            if (Character.isUpperCase(c)) {
                // Utilizing flipCase to convert the uppercase character to lowercase
                result.append(flipCase(String.valueOf(c)));
            } else {
                result.append(c);
            }
        }
        return result.toString();
    }
}